site_name: Brasil Channel

nav:
    - Inicio: 'index.md'
    - Panejamento:
        - Planejamento da equipe:
          - 'Ferramentas': './planejamento/ferramentas.md'
          
        - Planejamento do projeto:
          - 'Cronograma': './planejamento/cronograma.md'
          - 'Processo de Design': './planejamento/processo.md'
          - 'Sites avaliados': './planejamento/sites.md'
    - Análise de Requisitos:
        - 'Perfil de Usuário': './analiseRequisitos/perfilUsuario.md'
        - 'Personas': './analiseRequisitos/personas.md'
        - Análise de Tarefas: 
          - 'Analise Hierárquica': './analiseRequisitos/AnaliseDeTarefas/analiseTarefas.md'
          - 'Análise GOMS': './analiseRequisitos/AnaliseDeTarefas/analiseTarefa_Goms.md'
          - 'Análise CTT' : './analiseRequisitos/AnaliseDeTarefas/analiseTarefa_CTT.md'
        - 'Aspectos Éticos': './analiseRequisitos/aspectosEticos.md'
        - 'Principios Gerais do Projeto': './analiseRequisitos/principiosGerais.md'
        - 'Metas de Usabilidade': './analiseRequisitos/metas_Usabilidade.md'
        - 'Guia de Estilo': './analiseRequisitos/guiaDeEstilo.md'

    - Apresentações:
        - 'Ponto de controle 1': './apresentacoes/apresentacao1.md'
        - 'Ponto de controle 2': './apresentacoes/apresentacao2.md'
        - 'Ponto de controle 3': './apresentacoes/apresentacao3.md'

theme:
  name: material
  logo: assets/channel.png
  favicon: assets/channel.png
  palette:
    primary: green
